version: '3'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    tty: true
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistent volume for RabbitMQ data
    environment:
      RABBITMQ_DEFAULT_USER: 'cinecus'  # Set default RabbitMQ user
      RABBITMQ_DEFAULT_PASS: '123456'  # Set default RabbitMQ password
    ports:
        - "15672:15672"
        - "5672:5672"

  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Admin1234
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  rabbitmq_data:
    driver: local 
  sql_data:
    driver: local